import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Hero from '../components/Hero'
import Gallery from '../components/Gallery'
import Cards from '../components/Cards'
import React from 'react';
import ReactDOM from 'react-dom';



export default function Home() {
  return (
    <div className={styles.container}
    >
      <Head>
        <title> Rick and Morty | Wiki </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      < Hero/>

   
      <main className={styles.main}>


        <h1 className={styles.title}>
         Rick and Morty | Wiki
        </h1> 
        
        

        < Cards/>
        < Gallery/>

        


      </main>



    </div>

    

    
  )
}

